name: 'Comment on PR'
description: 'Create or update a message in Pull Request'
author: 'Kamil Kisiela <kamil.kisiela@gmail.com>'
inputs:
  message:
    description: 'Message'
    required: true
  bot:
    description: 'Name of the bot'
    required: true
  bot-token:
    description: 'GitHub Token of the bot'
    required: true  
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'message-circle'  
  color: 'purple'
