name: 'Comment on Pull Request'
description: 'Create or update a message in Pull Request'
author: 'Kamil Kisiela <kamil.kisiela@gmail.com>'
inputs:
  message:
    description: 'Message'
    required: true
  bot:
    description: 'Name of the bot'
    required: true
  bot-token:
    description: 'GitHub Token of the bot'
    required: true
  github-token:
    required: true
    description: 'Github Token to access repository'
  commentKey:
    required: false
    description: 'Identification key for the comment - used for editing purposes'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'  
  color: 'purple'
